"""Add metrics and incidents

Revision ID: c7315705cbf6
Revises: 951dc6153326
Create Date: 2026-02-17 23:01:40.998677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7315705cbf6'
down_revision: Union[str, Sequence[str], None] = '951dc6153326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('affected_endpoints', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('ai_action_items', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_time', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.BigInteger(), nullable=True),
    sa.Column('total_errors', sa.BigInteger(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_bucket_path', 'request_metrics', ['bucket_time', 'path', 'method', 'status_code'], unique=False)
    op.create_index(op.f('ix_request_metrics_bucket_time'), 'request_metrics', ['bucket_time'], unique=False)
    op.create_index(op.f('ix_request_metrics_id'), 'request_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_request_metrics_path'), 'request_metrics', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_metrics_path'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_bucket_time'), table_name='request_metrics')
    op.drop_index('idx_metrics_bucket_path', table_name='request_metrics')
    op.drop_table('request_metrics')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index('idx_incidents_status', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
